version: '3.2'

services:
  myqsl:
    image: mysql:5.7
    restart: always
    environment:
     - MYSQL_DATABASE=sandbox
     - MYSQL_USER=sysadm
     - MYSQL_PASSWORD=horosh
     - MYSQL_ROOT_PASSWORD=root
     - TZ=Europe/Moscow
    ports:
     - 3376:3306
    expose:
     - 3376
    volumes:
     - ./data:/root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    command: ['mysqld', '--login-path=client sandbox < create.sql']
#    command: ['mysqld_safe', '--skip-grant-tables']
#    , '--skip-grant-tables'
#    mysql --login-path=client sandbox < create.sql