version: '3.2'

services:
  myqsl:
    build:
      context: ./data 
    restart: always
    environment:
#     - MYSQL_DATABASE=sandbox
     - MYSQL_USER=sysadm
     - MYSQL_PASSWORD=horosh
     - MYSQL_ROOT_PASSWORD=root
     - TZ=Europe/Moscow
    ports:
     - 3376:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']